### ISSUE TITLE
Replies don't load when opening posts

### ISSUE THREAD

**Issue by Yowlen** [muesli/telephant#49] opened 2019-06-26 00:18 UTC
Title explains it all. Only the post being opened is loaded. No replies, nor the posts above it in the case of opening a reply to another post, ever get shown.

Tested using the prebuilt binary on Xubuntu 18.04.

Edit: Specifically, this seems to happen with posts from instances other than the one the account is on. Loading up my own thread works fine, as does other same-instance communication.

**Comment by muesli** [comment] 2019-06-26 04:11
Thanks for all your reports, really appreciate them!

I'm afraid I can't reproduce this one, though. I wonder if it was just an intermittent issue with your instance? Can you monitor the output on the terminal and see if it spits out any errors when trying to load the entire thread?

**Comment by Yowlen** [comment] 2019-06-26 04:53
I'll check on the terminal output tomorrow since I already shut down my computer for the night, but just to expand a bit for now:

Since making the original report, I've found a few from other instances that do work, but others still refuse to do so. It seems to happen more often with boosted posts.

I'll update as I get any new information.

**Comment by muesli** [comment] 2020-02-28 08:14
Should be fixed in master by 3136b93.

**Closed by muesli** 2020-02-28 08:14 UTC
Labels: bug
