### ISSUE TITLE
The authorisation token link doesn't seem to be going to the correct URL?

### ISSUE THREAD

**Issue by TrollDecker** [muesli/telephant#13] opened 2019-05-11 20:46 UTC
In trying to get an authorisation code, I found that instead of bringing up the authorisation request page, it was simply opening a new tab and going straight `/web/getting_started`. I was able to get around this by instead copying the URL generated in the console output and pasting it into Firefox and that worked A-OK.

I'm guessing the URL used in the POST request might be getting malformed or something? I'm not sure, because around that point, there wasn't any other feedback.

**Comment by muesli** [comment] 2019-05-11 21:01
Which server instance are you trying to connect to?

**Comment by TrollDecker** [comment] 2019-05-11 21:48
[social.diskseven.com](url)

**Comment by muesli** [comment] 2019-05-12 00:35
Ok, can't quite try it out with that instance, since its private & registrations are closed. However if you you managed to manually copy & paste the URL from the terminal, then that's the very same URL that should be opened when you click the link from inside the app.

**Comment by muesli** [comment] 2019-05-15 00:56
We're now also displaying the provided auth URL during the login process, where you can also copy it to your clipboard.

**Comment by muesli** [comment] 2019-05-17 14:31
Closing as I can't reproduce this with various instances I've tested Telephant with. If you still can, please provide as much info from the output as you can, and I'll happily investigate some more.

**Closed by muesli** 2019-05-17 14:31 UTC
